services:
  eng-center-db:
    image: postgres:17.5-alpine
    container_name: eng-center-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: eng-center
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - eng-center:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"]
    mem_limit: 800m
    mem_reservation: 256m
    ports:
      - 6379:6379
  eng-center:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: duongduyy/eng-center-app:lastest
    environment:
      - DATABASE_HOST=eng-center-db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=postgres
      - DATABASE_TYPE=postgres
      - DATABASE_SSL_MODE=false
      - DATABASE_CHANNEL_BINDING=require
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=qrdG2MLYcaPrLImYgF79gTQiS4z8wqkn
      - TZ=Asia/Ho_Chi_Minh
    expose:
      - 8080
    ports:
      - 8080:8080
volumes:
  eng-center: